test:
	python3 phase1.py 1k.xml
	diff terms.txt 1k-terms.txt
	diff emails.txt 1k-emails.txt
	diff dates.txt 1k-dates.txt
	diff recs.txt 1k-recs.txt

clean:
	rm -f terms.txt emails.txt dates.txt recs.txt